### ISSUE TITLE
Colabs won't work because of wrong path

### ISSUE THREAD

**Issue by cerkut** [CadenzaProject/cadenza_tutorials#1]
**Describe the bug**

Pressing the colab button on the jupyter book e.g., https://cadenzachallenge.org/cadenza_tutorials/metrics/correctness.html
Gives 
"There was an error loading this notebook. Ensure that the file is accessible and try again.
https://github.com/CadenzaProject/cadenza_tutorials/blob/main/docs/metrics/correctness.ipynb"

The correct path should be without /docs/ https://github.com/CadenzaProject/cadenza_tutorials/blob/main/metrics/correctness.ipynb

**Additional context**
Thanks for great a learning resource

**Comment by groadabike** [comment]
Hi @cerkut ,
Thank you so much for reporting this.
It is a bit odd considering that the Colab option is something added automatically by Jupyter Book. I will chack how to fix this.

**Comment by groadabike** [comment]
Hi @cerkut 
Found the issue, it was a  problem with the relative path to the notebooks.
Now it is fixed.

Thank you
